name: Release Workflow

on:
  push:
    branches:
      - main  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Electron application
        run: npm run build  

      - name: Bump Version
        id: version_bump
        run: |
          npm version patch --no-git-tag-version
          echo ::set-output name=new_version::$(node -p "require('./package.json').version")

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          repository: sattyap/releaser  
          tag_name: v${{ steps.version_bump.outputs.new_version }}
          release_name: Release ${{ steps.version_bump.outputs.new_version }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/*.zip  
          asset_name: test-${{ steps.version_bump.outputs.new_version }}.zip
          asset_content_type: application/zip
