name: Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Get latest tag
        id: get_tag
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          tag: ${{ env.tag }}
        run: |
          gh release create "$tag" \
              --repo="SattyaP/releaser" \
              --title="${tag#v}" \
              --generate-notes
