name: Release Workflow

on:
  push:
    branches:
      - main 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Read version from package.json
        id: get_version
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Read productName from package.json
        id: get_product_name
        run: echo "PRODUCT_NAME=$(node -p \"require('./package.json').productName\")" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Ensure it's referenced correctly
        with:
          repository: 'SattyaP/releaser'  # Specify the target repository
          tag_name: ${{ github.ref }}  # Using the tag that triggered the workflow
          release_name: "Release ${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Ensure it's referenced correctly
        with:
          repository: 'SattyaP/releaser'  # Specify the target repository
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/*.zip
          asset_name: "${{ env.PRODUCT_NAME }}-${{ env.VERSION }}.zip"
          asset_content_type: application/zip
